### ISSUE TITLE
AT-19: Generate directions for individuals with disabilities

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#107]
### User Story: CC-19 (#19)
As a user, I want to be able to select vertical transportation options so that I can view directions that consider my physical and mental needs.

### Acceptance Criteria
Given the user has opened the side-menu panel by selecting the hamburger menu button and clicking on the Settings option,  

The user should be able to select their preferred vertical transportation by enabling/disabling the toggle buttons. The directions should adjust accordingly in order to meet the user’s physical and mental needs.

**Comment by jodavimehran** [comment]
Accepted
