### ISSUE TITLE
AT-20: Highlight indoor points of interest on a campus building's floor map

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#108]
### User Story: CC-20 (#20)
As a user, I want to be able to select the visibility of access points (printers, washrooms, fountains, study rooms, fire escapes, elevators, stairs), so that my access points of choice can be highlighted on the indoor maps.

### Acceptance Criteria
Given the user has opened the side-menu panel by selecting the hamburger menu button and clicking on the Settings option,  

The user should be able to change the visibility of different access points and the indoor maps should get updated accordingly.

**Comment by jodavimehran** [comment]
Accepted
