### ISSUE TITLE
AT-21: Provide directions between rooms on different floors of a campus building

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#109]
### User Story: CC-21 (#21)
As a user, I want to be able to navigate between different floors of a campus building so that I can follow the path with my accessibility preferences.

### Acceptance Criteria
Given that the user has searched for an indoor location, clicked on the yellow navigation arrow to the right of the search result, and has set another indoor location on a different floor of the same building as the starting point,  

The user should be given a path from their starting location that respects their vertical navigation preferences. The user should also with instructions to reach the floor of the selected room and then the destination room.

**Comment by jodavimehran** [comment]
Accepted
