### ISSUE TITLE
AT-22: Obtain indoor and outdoor directions between the campuses

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#110]
### User Story: CC-22 (#22)
As a user, I want to be able to select a room from a different campus (from SWG campus to Loyola campus and vice versa) so that I can view the specific outdoor and indoor directions, including different commute options.

### Acceptance Criteria
Given that the user has searched for an indoor location, clicked on the yellow navigation arrow to the right of the search result, and has set another indoor location in another campus building as the starting point,  

The user should be given different commute options, including the shuttle bus option. Depending on the selection, the user should be given instructions from the inside of the initial building to the outdoors to the inside of the other campus’ building.

**Comment by jodavimehran** [comment]
Accepted
