### ISSUE TITLE
AT-23: View the nearest outdoor points of interest from a given location

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#111]
### User Story: CC-24 (#24)
As a user, I want to be able to view the nearest outdoor points of interest from the campuses so that I get customized results based on a selected category.

### Acceptance Criteria
Given the user has opened the side-menu panel by selecting the hamburger menu button and clicking on the Explore option,  

The user should be able to view different categories for the points of interest (food, drink, study). Once the selection made, the user should be able to see a list of points of interest around the campus for that category.

**Comment by jodavimehran** [comment]
Accepted
