### ISSUE TITLE
AT-24: Save locations for easy access

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#112]
### User Story: CC-36 (#36)
As a user, I want to be able to save my favourite locations so that I can easily locate them on the map.

### Acceptance Criteria
Given that the user has searched for a valid outdoor location, 

The user should see an information card appear at the bottom of the screen with a Save button. Once selected, the location will be stored on the side-menu option My Places.

**Comment by jodavimehran** [comment]
Accepted
