### ISSUE TITLE
AT-05: Search for a given outdoor location

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#79]
### User Story: CC-32 (#32)
As a user, I want to be able to search for a specific outdoor location so that I can readily find my desired point of interest.

### Acceptance Criteria
Assuming that the user is viewing the outdoor map or a Concordia building’s indoor floor map, 

The user should be able to type the name of their desired outdoor location and click on the result to see its placement on the map.  The map will also display a brief description of the location at the bottom of the screen.

**Comment by jodavimehran** [comment]
Accepted
