### ISSUE TITLE
AT-07: Set a campus building as the start or end point

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#80]
### User Story: CC-8 (#8 )
As a user, I want to be given a path on a map between a start and a destination point so that I can navigate between buildings on campus.

### Acceptance Criteria
To select the start/end destination, the user can either click on the directions button in the building info sheet which appears when clicking on a Concordia building or by using the search bar. Given that the user has set valid start and end points and began the navigation process, 

 A red path should be displayed on the map outlining the route between the two destinations. By default, the selected mode of transportation is by car.

**Comment by jodavimehran** [comment]
Accepted
