### ISSUE TITLE
AT-08: Select the preferred method of transportation

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#81]
### User Story: CC-9 (#9)
As a user, I want to be able to choose between multiple transportation methods (walk, car, public transportation) so that I can be accommodated by my available transportation method.

### Acceptance Criteria
Given the user has inputted the start and end points for navigation,  

The user should see the expected travel durations of each transportation method. Once the navigation process begins, a path will be displayed on the map to outline the corresponding route. A step by step navigation instructions and updated map views of the generated path are also displayed to the user.

**Comment by jodavimehran** [comment]
There is no way for the user to change the method of transportation after starting the navigation.

**Comment by jodavimehran** [comment]
The view will not change to the selected points in navigation mode in each step. For example, if in some step the user should turn left, the view should navigate to that point. But the view doesn't change when the user clicks on the arrow button and selects to go to the next step.

**Comment by Amanda-Kolopa** [comment]
Thank you for the feedback!
We will try to implement these changes in the following sprint.

**Comment by Amanda-Kolopa** [comment]
@jodavimehran 
Can you verify if this test is considered accepted, please? :slightly_smiling_face:

**Comment by jodavimehran** [comment]
> @jodavimehran
> Can you verify if this test is considered accepted, please? 🙂

Yes, I just forgot to do that.

**Comment by jodavimehran** [comment]
Accepted

**Comment by Amanda-Kolopa** [comment]
> > @jodavimehran
> > Can you verify if this test is considered accepted, please? slightly_smiling_face
> 
> Yes, I just forgot to do that.

No worries :smile: 
Thank you!
