### ISSUE TITLE
AT-09: Set user's current location as the starting point

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#82]
### User Story: CC-10 (#10)
As a user, I want to be able to use my current location as my start location so that I can quickly navigate to other locations. 

### Acceptance Criteria
Given that the user has granted permission to access their location and has set a campus building as the end point for navigation, 

The user should see that the default start point for any navigation is their current location. When selecting the start/end navigation points, the user should also see a button on the bottom-right side of the screen that sets their current location as a start or end point.

**Comment by jodavimehran** [comment]
Accepted
