### ISSUE TITLE
AT-10 : Select Concordia's shuttle bus service as a mode of transportation

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#83]
### User Story: CC-11 (#11)
As a user, I want to be able to also navigate between campuses (SGW and Loyola) by choosing the Concordia shuttle bus option so that I can easily find my way between campuses.

### Acceptance Criteria
Given the user has inputted the start point near campus and an end point near the opposite campus,  

The user should be able to select the shuttle bus as a mode of transportation and see the expected travel time to reach the destination. Once the navigation begins, the user should see the map view containing the path to the destination with step-by-step instructions.

**Comment by jodavimehran** [comment]
If you had implemented this feature just like the transportation methods, It would be much more user-friendly. In this way, the app can automatically select the nearest shuttle stop based on the chosen start point. For example, if the selected start point is the current location of the user and the user is located on EV building, the app can find out that the user wanted to use SGW to LOY shuttle.

Also, the app should show the navigation path to the user from the selected start point to the shuttle stop and also from the shuttle stop to the chosen destination. You can always consider walking as a transportation method from the selected location to the nearest shuttle stop and from the shuttle stop to the selected destination.
For example, assume that a user selects Hall building as a source and SP building as a destination and also select the Concordia shuttle as a transportation method. So the app should show the walking path from Hall building to the shuttle stop, which is somewhere near EV, and also at the end of the shuttle path, the app should show the walking path from the shuttle stop, which is somewhere near AD building, to the SP building.

**Comment by Amanda-Kolopa** [comment]
We originally planned to have the shuttle option displayed with the other modes of transportation but decided it would be better to have an overview of the available shuttle times in an easily accessible area. Regardless, we can move the functionality, it's no trouble :slightly_smiling_face: Although, the team was wondering if you could share your opinion on having both the side menu option and incorporating the feature with the other transportation modes.

As for the navigation path, the team agrees that it should be incorporated in the route and will be implemented during the sprint.

Thank you for the feedback!

**Comment by jodavimehran** [comment]
> We originally planned to have the shuttle option displayed with the other modes of transportation but decided it would be better to have an overview of the available shuttle times in an easily accessible area. Regardless, we can move the functionality, it's no trouble 🙂 Although, the team was wondering if you could share your opinion on having both the side menu option and incorporating the feature with the other transportation modes.
> 
> As for the navigation path, the team agrees that it should be incorporated in the route and will be implemented during the sprint.
> 
> Thank you for the feedback!

There is no problem if you want to keep the side menu option.

**Comment by Amanda-Kolopa** [comment]
> > We originally planned to have the shuttle option displayed with the other modes of transportation but decided it would be better to have an overview of the available shuttle times in an easily accessible area. Regardless, we can move the functionality, it's no trouble slightly_smiling_face Although, the team was wondering if you could share your opinion on having both the side menu option and incorporating the feature with the other transportation modes.
> > As for the navigation path, the team agrees that it should be incorporated in the route and will be implemented during the sprint.
> > Thank you for the feedback!
> 
> There is no problem if you want to keep the side menu option.

Perfect. Thanks again!

**Comment by jodavimehran** [comment]
Accepted
