### ISSUE TITLE
AT-13: Provide navigation to an upcoming Calendar event

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#84]
### User Story: CC-15 (#15)
As a user, I want to be able to get the direction to the location of my upcoming event in my selected calendar so that I can navigate between my planned events.

### Acceptance Criteria
Given that the user has previously synchronized their calendar events containing valid locations, 

By navigating to the schedule tab in the side menu, the user should be able to select an event to set it as the end point for navigation. The default start point is either set as the user’s current location (given location permission) or is left empty.

**Comment by jodavimehran** [comment]
I couldn't test this feature but I remember that it has been shown to me in the last meeting so it is Accepted.
