### ISSUE TITLE
AT-14: Obtain the location of a searched indoor point of interest

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#85]
### User Story: CC-25 (#25)
As a user, I want to be able to search for an indoor location so that I can determine its position on the floor map.

### Acceptance Criteria
Given that the user is viewing the outdoor map or a Concordia building’s indoor floor map, 

The user should be able to search for an available indoor location and see it highlighted on the indoor floor map.

**Comment by jodavimehran** [comment]
Accepted
