### ISSUE TITLE
AT-15: Navigate to different rooms on a specific floor in a campus building

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#86]
### User Story: CC-17 (#17)
As a user, I want to be able to navigate between two places on the same floor of a campus building so that I can travel to my indoor destination. 

### Acceptance Criteria
Given that the user has searched for an indoor location, clicked on the yellow navigation arrow to the right of the search result, and has set another indoor location on the same floor as the starting point,  

The user should be able to start the navigation process and see an overview of the path with an arrow pointing towards the destination.

**Comment by jodavimehran** [comment]
You should add an arrow on the drawn line to show the direction of the path.

**Comment by Amanda-Kolopa** [comment]
Thank you for the feedback!
We will try to implement this change in the following sprint.

**Comment by jodavimehran** [comment]
Accepted
