### ISSUE TITLE
AT-16: Show the shortest path directions to a destination in a campus building

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#87]
### User Story: CC-18 (#18)
As a user, I want to be able to view the shortest path, in terms of time, to an indoor point of interest so that I can reach my destination without performing additional travel efforts.

### Acceptance Criteria
Given that the user has searched for an indoor location, clicked on the blue navigation arrow to the right of the search result, and has set another indoor location on the same floor as the starting point, 

The user should see the shortest path between the start and end points on the indoor map.

**Comment by jodavimehran** [comment]
What is the difference between this user story and #86?

**Comment by Amanda-Kolopa** [comment]
User story #17 (or acceptance test #86) signifies the development efforts of drawing a general path between two indoor locations on the same floor. 

The purpose of user story #18 is to represent the additional development efforts for implementing the shortest path algorithm which will also encompass future navigations between different floors and campus buildings. We wanted to ensure the user efficiently reaches their destination as opposed to following a path containing non-essential travel.

**Comment by jodavimehran** [comment]
> User story #17 (or acceptance test #86) signifies the development efforts of drawing a general path between two indoor locations on the same floor.
> 
> The purpose of user story #18 is to represent the additional development efforts for implementing the shortest path algorithm which will also encompass future navigations between different floors and campus buildings. We wanted to ensure the user efficiently reaches their destination as opposed to following a path containing non-essential travel.

But from a user's point of view, there is no difference between these two features.

**Comment by Amanda-Kolopa** [comment]
> > User story #17 (or acceptance test #86) signifies the development efforts of drawing a general path between two indoor locations on the same floor.
> > The purpose of user story #18 is to represent the additional development efforts for implementing the shortest path algorithm which will also encompass future navigations between different floors and campus buildings. We wanted to ensure the user efficiently reaches their destination as opposed to following a path containing non-essential travel.
> 
> But from a user's point of view, there is no difference between these two features.

That is true. We must have forgotten to consider this while creating the user stories in the initial sprint.
Thank you for the insight, we will update the project backlog and document!
