### ISSUE TITLE
AT-17: Provide side menu to access app features

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#88]
### User Story: CC-65 (#65)
As a user, I want to be able to use a side menu so that I can easily access the various functionalities of the application.

### Acceptance Criteria
Given that the user has launched the application and completed viewing the splash screen, 

The user should be able to access the main system features through the side menu by selecting the hamburger menu option at the top left of the screen.

**Comment by jodavimehran** [comment]
This is not a user story! ;)

**Comment by Amanda-Kolopa** [comment]
Our apologies! :sweat_smile: 
We will remove it from our backlog and document. Thank you for the notification!
