### ISSUE TITLE
AT-18: Generate directions to an outdoor point of interest

### ISSUE THREAD

**Issue by Amanda-Kolopa** [RobertBeaudenon/SOEN390-CampusGuideMap#89]
### User Story: CC-26 (#26)
As a user, I want to be able to get the directions to the selected outdoor point of interest so that I can navigate to that location.

### Acceptance Criteria
Given that the user has searched for a valid outdoor location, clicked on the desired search result, and is seeing the description of the location at the bottom of the screen, 

 The user should be able to click on the Directions button at the bottom of the screen to set it as the end point for navigation. The user should also see the available modes of transportation.

**Comment by jodavimehran** [comment]
Accepted
